### ISSUE TITLE
omg doxxed

### ISSUE THREAD

**Issue by gequify** [NotJINXZ/Ethereal#1]
omg jinx doxxed me help!

**Comment by NotJINXZ** [comment]
💀

**Comment by gequify** [comment]
> 💀

reporting this to the CIA and sir this will be DMCA'D

**Comment by gequify** [comment]
> 💀

![bleh-meme-bleh](https://github.com/NotJINXZ/Ethereal/assets/152816624/b2fa0e8d-6d5d-4bfc-b18c-b9257515c2ca)
